### ISSUE TITLE
 user will be automatically logged out after a while in docker 

### ISSUE THREAD

**Issue by changchichung** [JhumanJ/OpnForm#333]
users will be automatically logged out of Opform, and won’t be able to log in again. 
docker restart is required to resolve this.

browser logs
```
auth.js:49 
 No user, logging out.
setUser	@	auth.js:49
api/login:1 
 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
useOpnApi.js:67 
 Request error 500
onResponseError	@	useOpnApi.js:67
LoginForm.vue:98 
 FetchError: [POST] "http://192.168.100.2:8007/api/login": 500 Internal Server Error
    at async o (ofetch.00501375.mjs:261:15)
(匿名)	@	LoginForm.vue:98
useOpnApi.js:75 
 
 POST http://192.168.100.2:8007/api/login 500 (Internal Server Error)
dv	@	useOpnApi.js:75
(匿名)	@	Form.js:125
submit	@	Form.js:124
post	@	Form.js:89
login	@	LoginForm.vue:84
(匿名)	@	LoginForm.vue:5
顯示 6 個其他框架
useOpnApi.js:67 
 Request error 500
onResponseError	@	useOpnApi.js:67
await in s (非同步)		
dv	@	useOpnApi.js:75
(匿名)	@	Form.js:125
submit	@	Form.js:124
post	@	Form.js:89
login	@	LoginForm.vue:84
(匿名)	@	LoginForm.vue:5
顯示 6 個其他框架
LoginForm.vue:98 
 FetchError: [POST] "http://192.168.100.2:8007/api/login": 500 Internal Server Error
    at async o (ofetch.00501375.mjs:261:15)
(匿名)	@	LoginForm.vue:98
Promise.catch (非同步)		
login	@	LoginForm.vue:97
(匿名)	@	LoginForm.vue:5
顯示 4 個其他框架
```

**Comment by JhumanJ** [comment]
Can you please share the logs?

**Comment by JhumanJ** [comment]
Can you please share the logs from laravel.log? It seems like there are some back-end issues going on here

**Comment by JhumanJ** [comment]
Fixed in https://github.com/JhumanJ/OpnForm/pull/369
