### ISSUE TITLE
Freshly self-hosted 1.3.2 issues

### ISSUE THREAD

**Issue by asrulmunir** [JhumanJ/OpnForm#542]
I created a new VM in GCP - Ubuntu  22.04 LTS.

These were all the commands that I use:

```
sudo apt install docker-compose
sudo usermod -aG docker ${USER}
sudo apt install pip
sudo reboot
git clone https://github.com/JhumanJ/OpnForm.git
cd OpnForm/
./scripts/setup-env.sh --docker
ls -a
vi api/.env
vi client/.env
vi docker-compose.yml 
docker-compose up -d

```

These are the only changes on the api/.env:

```
APP_URL
MAIL_*
OPEN_AI_API_KEY
```

No change on client/.env and docker-compose.yml.

Home page and login page able to load without problem, but unable to login.

Browser console:

```
Failed to load resource: the server responded with a status of 500 () https://domainname/api/login
[Error] Request error – 500
	(anonymous function) (BFqPTobC.js:30:13104)
	onResponseError (BFqPTobC.js:30:13124)
	(anonymous function) (BFqPTobC.js:18:29062)

```

docker logs opnform_api-worker_1:

```
Backing up initial storage directory
mv: cannot move './storage' to '/etc/initial-storage': Device or resource busy
Initialising blank storage dir
cp: cannot stat '/etc/initial-storage': No such file or directory
chmod: cannot access '/persist/storage': No such file or directory

```

docker logs opnform_ingress_1:

```
[27/Aug/2024:12:24:09 +0000] "GET /api/templates?limit=10 HTTP/1.1" 500 44 "https://mynodip.tapirapi.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"

```

docker logs opnform_db_1:

```
2024-08-27 12:10:07.137 UTC [71] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-08-27 12:10:07.137 UTC [71] DETAIL:  Key (relname, relnamespace)=(migrations_id_seq, 2200) already exists.

```

docker logs opnform_ui_1:

```
Warning: .env file not found
Running node node ./server/index.mjs
Listening on http://[::]:3000
[Vue Router warn]: Alias "/oauth/:provider/callback" and the original record: "/oauth/callback" must have the exact same param named "provider"
[Vue Router warn]: Alias "/settings/connections/callback/:service" and the original record: "/settings/connections" must have the exact same param named "service"
```
docker logs opnform_api_1:

```
Backing up initial storage directory
mv: cannot move './storage' to '/etc/initial-storage': Device or resource busy
Initialising blank storage dir
cp: cannot stat '/etc/initial-storage': No such file or directory
chmod: cannot access '/persist/storage': No such file or directory
Waiting for DB to be ready
Running DB Migrations

   INFO  Preparing database.  

  Creating migration table ..................................... 483.23ms FAIL
[2024-08-27 12:10:07] local.DEBUG: Un-handled Exception: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(migrations_id_seq, 2200) already exists. (Connection: pgsql, SQL: create table "migrations" ("id" serial not null primary key, "migration" varchar(255) not null, "batch" integer not null)) {"exception":"[object] (Illuminate\\Database\\UniqueConstraintViolationException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"
DETAIL:  Key (relname, relnamespace)=(migrations_id_seq, 2200) already exists. (Connection: pgsql, SQL: create table \"migrations\" (\"id\" serial not null primary key, \"migration\" varchar(255) not null, \"batch\" integer not null)) at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:820)
[stacktrace]

```

**Comment by JhumanJ** [comment]
I just released a new version. Can you please give this another try using the latest version?

My reproduction:

```bash
coding git clone https://github.com/JhumanJ/OpnForm.git todelete
Cloning into 'todelete'...
remote: Enumerating objects: 13530, done.
remote: Counting objects: 100% (2613/2613), done.
remote: Compressing objects: 100% (962/962), done.
remote: Total 13530 (delta 1985), reused 1847 (delta 1637), pack-reused 10917 (from 1)
Receiving objects: 100% (13530/13530), 28.30 MiB | 5.82 MiB/s, done.
Resolving deltas: 100% (9086/9086), done.
➜  coding cd todelete
➜  todelete git:(main) ./scripts/setup-env.sh --docker

OpnForm setup detected the --docker flag. Preparing Docker-specific environment...
Creating OpnForm's main .env file from the template...
Creating OpnForm's client .env file from the template...
✅ OpnForm environment setup is now complete. Enjoy building your forms!
➜  todelete git:(main) ls -a api
.                      artisan                public
..                     bootstrap              resources
.env                   composer.json          routes
.env.docker            composer.lock          server.php
.env.example           config                 storage
.gitignore             database               tests
_ide_helper_models.php phpunit.xml            vapor.yml
app                    pint.json

➜  todelete git:(main) docker-compose up -d

[+] Running 6/0
 ✔ Container todelete-redis-1       Running                                                                         0.0s
 ✔ Container todelete-api-1         Running                                                                         0.0s
 ✔ Container todelete-ui-1          Running                                                                         0.0s
 ✔ Container todelete-api-worker-1  Running                                                                         0.0s
 ✔ Container todelete-db-1          Running                                                                         0.0s
 ✔ Container todelete-ingress-1     Started                                                                         0.1s
➜  todelete git:(main)
```
- Go to http://localhost/login 
- Login `admin@opnform.com` & `password`
- You're in 🥳

**Comment by Darkstepan** [comment]
I tried doing it on the new version and I am facing the same issue.

```
git clone https://github.com/JhumanJ/OpnForm.git --depth=1
cd OpnForm/
./scripts/setup-env.sh --docker
# change local ingress port from 80 to 4096 in docker-compose.yml
# change APP_URL in api/.env to match the real url
docker compose up -d
```

Attempted to log in using the provided credentials at /login

Browser Console: 
```Failed to load resource: the server responded with a status of 500 (Internal Server Error)
useOpnApi.js:74 Request error 500
onResponseError @ useOpnApi.js:74
```

docker compose logs:

```
opnform-api-1         | NOTICE: PHP message: [2024-08-27 17:05:43] local.DEBUG: Un-handled Exception: fopen(/usr/share/nginx/html/storage/framework/cache/data/c9/f7/c9f72bb747fca455917dc9e32e1ed586972f59ed): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): fopen(/usr/share/nginx/html/storage/framework/cache/data/c9/f7/c9f72bb747fca455917dc9e32e1ed586972f59ed): Failed to open stream: No such file or directory at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php:69)
opnform-api-1         | [stacktrace]
opnform-api-1         | #0 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'fopen(/usr/shar...', '/usr/share/ngin...', 69)
opnform-api-1         | #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'fopen(/usr/shar...', '/usr/share/ngin...', 69)
opnform-api-1         | #2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php(69): fopen('/usr/share/ngin...', 'c+')
opnform-api-1         | #3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php(42): Illuminate\\Filesystem\\LockableFile->createResource('/usr/share/ngin...', 'c+')
opnform-api-1         | #4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(108): Illuminate\\Filesystem\\LockableFile->__construct('/usr/share/ngin...', 'c+')
opnform-api-1         | #5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(345): Illuminate\\Cache\\FileStore->add('348cd11131529c4...', 1724778403, 60)
opnform-api-1         | #6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(131): Illuminate\\Cache\\Repository->add('348cd11131529c4...', 1724778403, 60)
opnform-api-1         | #7 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(116): Illuminate\\Cache\\RateLimiter->increment('348cd11131529c4...', 60)
opnform-api-1         | #8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(158): Illuminate\\Cache\\RateLimiter->hit('348cd11131529c4...', 60)
opnform-api-1         | #9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(92): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
opnform-api-1         | #10 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '100', '1')
opnform-api-1         | #11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
opnform-api-1         | #13 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #14 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #15 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #17 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
opnform-api-1         | #18 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
opnform-api-1         | #19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
opnform-api-1         | #20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
opnform-api-1         | #21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
opnform-api-1         | #22 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #23 /usr/share/nginx/html/vendor/laravel/vapor-core/src/Http/Middleware/ServeStaticAssets.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #24 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Vapor\\Http\\Middleware\\ServeStaticAssets->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #25 /usr/share/nginx/html/app/Http/Middleware/AcceptsJsonMiddleware.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #26 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AcceptsJsonMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #27 /usr/share/nginx/html/app/Http/Middleware/CustomDomainRestriction.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #28 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\CustomDomainRestriction->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #29 /usr/share/nginx/html/app/Http/Middleware/AuthenticateJWT.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #30 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AuthenticateJWT->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #31 /usr/share/nginx/html/app/Http/Middleware/SetLocale.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #32 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #33 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #34 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #35 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #36 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #37 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #38 /usr/share/nginx/html/app/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #39 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeli...
opnform-api-1         | NOTICE: PHP message: [2024-08-27 17:05:43] local.ERROR: fopen(/usr/share/nginx/html/storage/framework/cache/data/c9/f7/c9f72bb747fca455917dc9e32e1ed586972f59ed): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): fopen(/usr/share/nginx/html/storage/framework/cache/data/c9/f7/c9f72bb747fca455917dc9e32e1ed586972f59ed): Failed to open stream: No such file or directory at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php:69)
opnform-api-1         | [stacktrace]
opnform-api-1         | #0 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'fopen(/usr/shar...', '/usr/share/ngin...', 69)
opnform-api-1         | #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'fopen(/usr/shar...', '/usr/share/ngin...', 69)
opnform-api-1         | #2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php(69): fopen('/usr/share/ngin...', 'c+')
opnform-api-1         | #3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php(42): Illuminate\\Filesystem\\LockableFile->createResource('/usr/share/ngin...', 'c+')
opnform-api-1         | #4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(108): Illuminate\\Filesystem\\LockableFile->__construct('/usr/share/ngin...', 'c+')
opnform-api-1         | #5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(345): Illuminate\\Cache\\FileStore->add('348cd11131529c4...', 1724778403, 60)
opnform-api-1         | #6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(131): Illuminate\\Cache\\Repository->add('348cd11131529c4...', 1724778403, 60)
opnform-api-1         | #7 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(116): Illuminate\\Cache\\RateLimiter->increment('348cd11131529c4...', 60)
opnform-api-1         | #8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(158): Illuminate\\Cache\\RateLimiter->hit('348cd11131529c4...', 60)
opnform-api-1         | #9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(92): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
opnform-api-1         | #10 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '100', '1')
opnform-api-1         | #11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
opnform-api-1         | #13 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #14 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #15 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #17 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
opnform-api-1         | #18 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
opnform-api-1         | #19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
opnform-api-1         | #20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
opnform-api-1         | #21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
opnform-api-1         | #22 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #23 /usr/share/nginx/html/vendor/laravel/vapor-core/src/Http/Middleware/ServeStaticAssets.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #24 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Vapor\\Http\\Middleware\\ServeStaticAssets->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #25 /usr/share/nginx/html/app/Http/Middleware/AcceptsJsonMiddleware.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #26 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AcceptsJsonMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #27 /usr/share/nginx/html/app/Http/Middleware/CustomDomainRestriction.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #28 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\CustomDomainRestriction->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #29 /usr/share/nginx/html/app/Http/Middleware/AuthenticateJWT.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #30 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\AuthenticateJWT->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #31 /usr/share/nginx/html/app/Http/Middleware/SetLocale.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #32 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #33 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #34 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #35 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #36 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-api-1         | #37 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #38 /usr/share/nginx/html/app/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-api-1         | #39 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): ...
opnform-ingress-1     | 145.224.105.230 - - [27/Aug/2024:17:05:43 +0000] "POST /api/login HTTP/1.1" 500 44 "http://**REDACTED**/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
opnform-api-1         | 192.168.224.3 -  27/Aug/2024:17:05:43 +0000 "POST /index.php" 500
```

**Comment by asrulmunir** [comment]
> ```shell
> ./scripts/setup-env.sh --docker
> ```

Same issue :(

```
$ docker logs opnform_api_1
Backing up initial storage directory
mv: cannot move './storage' to '/etc/initial-storage': Device or resource busy
Initialising blank storage dir
cp: cannot stat '/etc/initial-storage': No such file or directory
chmod: cannot access '/persist/storage': No such file or directory
```

```
$ docker logs opnform_api-worker_1
Backing up initial storage directory
mv: cannot move './storage' to '/etc/initial-storage': Device or resource busy
Initialising blank storage dir
cp: cannot stat '/etc/initial-storage': No such file or directory
chmod: cannot access '/persist/storage': No such file or directory
```

**Comment by JhumanJ** [comment]
I finally managed to reproduce this on ubuntu and fix it, please try again https://github.com/JhumanJ/OpnForm/tree/v1.3.5
