### ISSUE TITLE
SMTP Configured but Emails Not Being Delivered

### ISSUE THREAD

**Issue by siddhantprateek** [JhumanJ/OpnForm#555]
I've configured my SMTP settings as follows:

```
MAIL_HOST=<mail-host>
MAIL_PORT=587
MAIL_USERNAME=<mail-user>
MAIL_PASSWORD=<mail-pwd>
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=admin@example.com
MAIL_FROM_NAME=OpnForm
```

However, I'm encountering an issue where, despite receiving a success message for invitation sends, no actual emails are being delivered. and for forget password i'm getting `server error` in the console.

**Comment by JhumanJ** [comment]
Hi, please give us the content of `laravel.log`. You can also try setting `APP_DEBUG=true` to get a proper error instead of just server error

**Comment by siddhantprateek** [comment]
sure, this is the log that i'm getting, when i try to reset password, hope this will work for you?
```
opnform-ops-api-1  | NOTICE: PHP message: [2024-09-04 06:19:28] local.DEBUG: Un-handled Exception: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
opnform-ops-api-1  | [stacktrace]
opnform-ops-api-1  | #0 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false, '', true, 'php')
opnform-ops-api-1  | #1 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
opnform-ops-api-1  | #2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build(Object(Closure))
opnform-ops-api-1  | #3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
opnform-ops-api-1  | #4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
opnform-ops-api-1  | #5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make('blade.compiler', Array)
opnform-ops-api-1  | #6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(168): Illuminate\\Foundation\\Application->make('blade.compiler')
opnform-ops-api-1  | #7 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
opnform-ops-api-1  | #8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Engines/EngineResolver.php(55): call_user_func(Object(Closure))
opnform-ops-api-1  | #9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(326): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
opnform-ops-api-1  | #10 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(288): Illuminate\\View\\Factory->getEngineFromPath('/usr/share/ngin...')
opnform-ops-api-1  | #11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(160): Illuminate\\View\\Factory->viewInstance('notifications::...', '/usr/share/ngin...', Array)
opnform-ops-api-1  | #12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(65): Illuminate\\View\\Factory->make('notifications::...', Array)
opnform-ops-api-1  | #13 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(114): Illuminate\\Mail\\Markdown->render('notifications::...', Array)
opnform-ops-api-1  | #14 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(236): Illuminate\\Notifications\\Channels\\MailChannel->Illuminate\\Notifications\\Channels\\{closure}(Array)
opnform-ops-api-1  | #15 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(441): value(Object(Closure), Array)
opnform-ops-api-1  | #16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(420): Illuminate\\Mail\\Mailer->renderView(Object(Closure), Array)
opnform-ops-api-1  | #17 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(313): Illuminate\\Mail\\Mailer->addContent(Object(Illuminate\\Mail\\Message), Object(Closure), Object(Closure), NULL, Array)
opnform-ops-api-1  | #18 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(66): Illuminate\\Mail\\Mailer->send(Object(Closure), Array, Object(Closure))
opnform-ops-api-1  | #19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\User), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\User), 'd6230923-906c-4...', Object(App\\Notifications\\ResetPassword), 'mail')
opnform-ops-api-1  | #21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
opnform-ops-api-1  | #22 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
opnform-ops-api-1  | #23 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #24 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #25 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(App\\Models\\User), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #26 /usr/share/nginx/html/app/Models/User.php(138): App\\Models\\User->notify(Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #27 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(83): App\\Models\\User->sendPasswordResetNotification('bea103d0f90b22b...')
opnform-ops-api-1  | #28 /usr/share/nginx/html/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php(35): Illuminate\\Auth\\Passwords\\PasswordBroker->sendResetLink(Object(SensitiveParameterValue))
opnform-ops-api-1  | #29 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\ForgotPasswordController->sendResetLinkEmail(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #30 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('sendResetLinkEm...', Array)
opnform-ops-api-1  | #31 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\ForgotPasswordController), 'sendResetLinkEm...')
opnform-ops-api-1  | #32 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
opnform-ops-api-1  | #33 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
opnform-ops-api-1  | #34 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #35 /usr/share/nginx/html/app/Http/Middleware/RedirectIfAuthenticated.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #36 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #37 /usr/share/nginx/html/app/Http/Middleware/RedirectIfAuthenticated.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #38 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
opnform-ops-api-1  | #39 /usr/share/nginx/html/app/Http/Middleware/ImpersonationMiddleware.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #40 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ImpersonationMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #41 /usr/share/nginx/html/app/Http/Middleware/SelfHostedCredentialsMiddleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #42 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SelfHostedCredentialsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #4...
opnform-ops-api-1  | NOTICE: PHP message: [2024-09-04 06:19:28] local.ERROR: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)
opnform-ops-api-1  | [stacktrace]
opnform-ops-api-1  | #0 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(97): Illuminate\\View\\Compilers\\Compiler->__construct(Object(Illuminate\\Filesystem\\Filesystem), false, '', true, 'php')
opnform-ops-api-1  | #1 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(931): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
opnform-ops-api-1  | #2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build(Object(Closure))
opnform-ops-api-1  | #3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve('blade.compiler', Array, true)
opnform-ops-api-1  | #4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve('blade.compiler', Array)
opnform-ops-api-1  | #5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make('blade.compiler', Array)
opnform-ops-api-1  | #6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php(168): Illuminate\\Foundation\\Application->make('blade.compiler')
opnform-ops-api-1  | #7 [internal function]: Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
opnform-ops-api-1  | #8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Engines/EngineResolver.php(55): call_user_func(Object(Closure))
opnform-ops-api-1  | #9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(326): Illuminate\\View\\Engines\\EngineResolver->resolve('blade')
opnform-ops-api-1  | #10 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(288): Illuminate\\View\\Factory->getEngineFromPath('/usr/share/ngin...')
opnform-ops-api-1  | #11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(160): Illuminate\\View\\Factory->viewInstance('notifications::...', '/usr/share/ngin...', Array)
opnform-ops-api-1  | #12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(65): Illuminate\\View\\Factory->make('notifications::...', Array)
opnform-ops-api-1  | #13 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(114): Illuminate\\Mail\\Markdown->render('notifications::...', Array)
opnform-ops-api-1  | #14 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(236): Illuminate\\Notifications\\Channels\\MailChannel->Illuminate\\Notifications\\Channels\\{closure}(Array)
opnform-ops-api-1  | #15 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(441): value(Object(Closure), Array)
opnform-ops-api-1  | #16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(420): Illuminate\\Mail\\Mailer->renderView(Object(Closure), Array)
opnform-ops-api-1  | #17 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(313): Illuminate\\Mail\\Mailer->addContent(Object(Illuminate\\Mail\\Message), Object(Closure), Object(Closure), NULL, Array)
opnform-ops-api-1  | #18 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(66): Illuminate\\Mail\\Mailer->send(Object(Closure), Array, Object(Closure))
opnform-ops-api-1  | #19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send(Object(App\\Models\\User), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable(Object(App\\Models\\User), 'd6230923-906c-4...', Object(App\\Notifications\\ResetPassword), 'mail')
opnform-ops-api-1  | #21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
opnform-ops-api-1  | #22 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\\Notifications\\NotificationSender->withLocale(NULL, Object(Closure))
opnform-ops-api-1  | #23 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #24 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Database\\Eloquent\\Collection), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #25 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send(Object(App\\Models\\User), Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #26 /usr/share/nginx/html/app/Models/User.php(138): App\\Models\\User->notify(Object(App\\Notifications\\ResetPassword))
opnform-ops-api-1  | #27 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(83): App\\Models\\User->sendPasswordResetNotification('bea103d0f90b22b...')
opnform-ops-api-1  | #28 /usr/share/nginx/html/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php(35): Illuminate\\Auth\\Passwords\\PasswordBroker->sendResetLink(Object(SensitiveParameterValue))
opnform-ops-api-1  | #29 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\ForgotPasswordController->sendResetLinkEmail(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #30 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('sendResetLinkEm...', Array)
opnform-ops-api-1  | #31 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\ForgotPasswordController), 'sendResetLinkEm...')
opnform-ops-api-1  | #32 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
opnform-ops-api-1  | #33 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
opnform-ops-api-1  | #34 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #35 /usr/share/nginx/html/app/Http/Middleware/RedirectIfAuthenticated.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #36 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #37 /usr/share/nginx/html/app/Http/Middleware/RedirectIfAuthenticated.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #38 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
opnform-ops-api-1  | #39 /usr/share/nginx/html/app/Http/Middleware/ImpersonationMiddleware.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #40 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ImpersonationMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #41 /usr/share/nginx/html/app/Http/Middleware/SelfHostedCredentialsMiddleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
opnform-ops-api-1  | #42 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SelfHostedCredentialsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
opnform-ops-api-1  | #43 /usr/share/nginx/htm...
```

**Comment by JhumanJ** [comment]
Please add `CACHE_DRIVER=redis` and make sure you have `MAIL_MAILER=smtp` in your `api/.env`. Should resolve it! I just added this as default for the docker setup

**Comment by siddhantprateek** [comment]
These settings, `CACHE_DRIVER=redis` and `MAIL_MAILER=smtp`, are already configured, but the issue arises after that.

**Comment by siddhantprateek** [comment]
```
SELF_HOSTED=false
APP_NAME=OpnForm
APP_ENV=local
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=https://mydomain.com
NUXT_PUBLIC_APP_URL=/
NUXT_PUBLIC_API_BASE=/api
NUXT_PRIVATE_API_BASE=http://ingress/api
NUXT_PUBLIC_ENV=dev
LOG_CHANNEL=errorlog
BROADCAST_CONNECTION=log
LOG_LEVEL=debug
DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=opnform
DB_USERNAME=postgres
DB_PASSWORD=<pwd>
FILESYSTEM_DRIVER=local
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=25
MAIL_USERNAME=<myusername>
MAIL_PASSWORD=<mypassw>
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=mydomain.com
MAIL_FROM_NAME=OpnForm
JWT_TTL=1440
AWS_ACCESS_KEY_ID=minio
AWS_SECRET_ACCESS_KEY=
AWS_URL=https://mydomain.com:2222
AWS_ENDPOINT=https://mydomain.com:2222
AWS_BUCKET=opnform
AWS_DEFAULT_REGION=us-east-1
PUSHER_APP_CLUSTER=mt1
FRONT_URL=https://mydomain.com


APP_KEY=base64:o+FMu/+lvAHJL<some-random>/vtiuzK8z==
JWT_SECRET=TIFZE8dVniK05b<some-random>LQkeTGapBgXaTWu
NUXT_API_SECRET=fE633JW<some-random>ZhcbSwNR
FRONT_API_SECRET=fE633JWIQ<some-random>4WQ0ZhcbSlNR
```
this is my configuration looks like

**Comment by JhumanJ** [comment]
Where is this file? You should have 2 different .env files it seems like you got everything mixed here. Did you [use our script](https://docs.opnform.com/deployment/docker) to generate the env files? More about env files here: https://docs.opnform.com/configuration/environment-variables

**Comment by siddhantprateek** [comment]
yeah, i've used your script generate env the files, i just got everything under single env file

**Comment by JhumanJ** [comment]
Can you try connecting to the api instance, and run the following commands?

```
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```
